### PR TITLE
Add options for font size for python

### PR DESCRIPTION
**Pull request by MixedMatched**
- [x] Functionality
- [x] Translation
- [x] Weird settings childLabels

Also, when @RedGl0w adds per-app settings, this should be moved to the python app.
Based on @0b101's PR #937.

~As for the childLabel oddities, I originally thought the problem would trace back to when I removed preferences_controller from main_controller in #65, but the code appears to be the same. Even more odd, when the preference for one of the labels is changed, it only changes the correct instance of the label, but when the language is changed, both change to the new language. When you do both, the language of both changes, but the corresponding option for the labels stays the same for both.~ It was a problem in not setting the message to default after displaying new cells.

### CODE REVIEW

**Comment by RedGl0w** [comment]
I think the setting should be in accessibility submenu, and not in the main controller...

**Comment by MixedMatched** [comment]
Why would it be accessibility? By default it's large and I can't imagine someone making the font smaller to see it better.

**Comment by 0b101** [comment]
Can you create a pull request of this on numworks/epsilon too?

**Comment by quentinguidee** [comment]
Is this feature likely to be accepted on Epsilon? (if yes, don't hesitate)

**Comment by 0b101** [comment]
It sounded like they liked the idea back when I proposed it, so there is a chance that it would be merged

**Comment by cent20net** [comment]
Add options for font size for python : Good idea !

**Comment by quentinguidee** [comment]
@MixedMatched We could put it by default in small, and in accessibility in big, no ?

**Comment by quentinguidee** [comment]
Bug fixed by #199 

We'll revert this PR soon, because the font size option is now available upstream, so #199 must be reverted too.

**Comment by quentinguidee** [comment]
@all-contributors please add @MixedMatched for code, ideas and question

**Pull request merged**
