### PR TITLE
[Feature] Backlight settings

### PR DESCRIPTION
**Pull request by RedGl0w**
This close : https://github.com/Omega-Numworks/Omega/issues/275, #3 and https://github.com/Omega-Numworks/Omega/issues/175

Based on https://github.com/numworks/epsilon/pull/910

Screenshots :
image
image

Todo :

- [ ] Add the translations for the keyboard shortcut

### CODE REVIEW

**Comment by quentinguidee** [comment]
It's really cool! Thank you! :)

I have some suggestions for this :
* The "brightness shortcut" slider is not easy to use. I suggest to replace it with a text field ? In the current state we don't know what we do exactly with the slider.
* The first text field has a problem : it hides the borders of the cell. I think we must fix the height of each cells.
* The `Luminosity` cell is too big
* I think the slider should stay in the first page, and then you can also edit its settings in another cell

**Comment by RedGl0w** [comment]
>     * The "brightness shortcut" slider is not easy to use. I suggest to replace it with a text field ? In the current state we don't know what we do exactly with the slider.
The slider isn't very easy to use, I know, but it is very clear for the min and max value, whereas a text input isn't...
>     * The first text field has a problem : it hides the borders of the cell. I think we must fix the height of each cells.
Escher...
>     * The `Luminosity` cell is too big
Escher...
>     * I think the slider should stay in the first page, and then you can also edit its settings in another cell
I think we could just bind the minus and plus keys to these functions

**Comment by quentinguidee** [comment]
> > ```
> > * The "brightness shortcut" slider is not easy to use. I suggest to replace it with a text field ? In the current state we don't know what we do exactly with the slider.
> > ```
> 
> The slider isn't very easy to use, I know, but it is very clear for the min and max value, whereas a text input isn't...
> 

We could simply do this : if the user put something > to the value, we reset the value to the max one. Same for values < 1.

> 
> > ```
> > * I think the slider should stay in the first page, and then you can also edit its settings in another cell
> > ```
> 
> 
> I think we could just bind the minus and plus keys to these functions

Yes but everyone doesn't use the shortcuts. Many people don't know them... So for them the luminosity settings are harder to use on Omega. We don't want that... :/

> Escher...

We'll fix that

**Comment by RedGl0w** [comment]
Fixed
image
image

**Comment by LeGmask** [comment]
it missing the size of the box

**Pull request closed without merging**
