### PR TITLE
up and right inverted in the function get_keys()

### PR DESCRIPTION
**Pull request by elicolh**

### CODE REVIEW

**Comment by quentinguidee** [comment]
Hi! Thanks for this Pull Request! Are you in the Discord?

**Comment by quentinguidee** [comment]
Huh can you recreate this PR ? You did it on the wrong branch :/ You must do it in the omega-dev branch :/ Thank you!

**Comment by elicolh** [comment]
hi, can I get the discord link?
should I still recreate the pull request?

**Comment by quentinguidee** [comment]
The Discord link is in the readme on the blue button 😉 https://discord.gg/hjH3gtd

And yes, I tried to rebase it but it gets conflicts. For any contributions, you should PR on the omega-dev branch, because this way we can try 1.19 without modifying 1.18.

See the wiki for more info : https://github.com/Omega-Numworks/Omega/wiki/Contributing

**Pull request closed without merging**
