### PR TITLE
Show more calculations

### PR DESCRIPTION
**Pull request by 0b101**
I have no idea if this still works, however, it shouldn't be too hard to fix any conflicts. Please see https://github.com/numworks/epsilon/pull/954 for the description and images.

### CODE REVIEW

**Comment by quentinguidee** [comment]
Hi! Thanks for this PR! It's definitely something I want to merge in Omega since a long time!

**Comment by RedGl0w** [comment]
I think this should be an option in the settings, and not imposed to the user.
It should be simple to had an option and to resolve conflict...
Going to work on it !

**Comment by 0b101** [comment]
I was planning on rewriting parts of this due to some issues that it caused. I’ll start working on it right away and I should have it posted soon enough.

**Comment by quentinguidee** [comment]
Perfect! Thank you @0b101 !!

**Comment by quentinguidee** [comment]
@0b101 Can I have your name to add it in the contributors list? (if you want!)

**Comment by 0b101** [comment]
@quentinguidee Yes, can you do either “0b101” or “David (0b101)”?

**Comment by quentinguidee** [comment]
@0b101 To keep the contributors list readable, I propose this : #89

**Comment by 0b101** [comment]
image

I didn't create the setting yet, but I think I got result formatting working

**Comment by M4xi1m3** [comment]
Amazing !
I only have one detail that bothers me, maybe you could prevent displaying things that doesn't simplify (like the line in your screenshot with the tan and cos) and only print the numerical value?

**Comment by quentinguidee** [comment]
@M4xi1m3 I don't know.. When I see the same think, I can know that my calculation doesn't simplify. If we hide that, I think we loose an information.. ?

**Comment by M4xi1m3** [comment]
I was asking myself that question. I think the fact that you can only see the approximate value shows that the calc can't simplify more.

**Comment by quentinguidee** [comment]
yes, but the user must know that... So it should be another setting I think.

**Comment by 0b101** [comment]
I'll upload what I have so far if that helps. I might have to close this request and open a new one though.

**Comment by 0b101** [comment]
closing. expect a new pull request shortly.

**Comment by quentinguidee** [comment]
Thank you :)))

**Pull request closed without merging**
