### PR TITLE
FCC ID always higlight fix

### PR DESCRIPTION
**Pull request by LeGmask**

### CODE REVIEW

**Comment by quentinguidee** [comment]
GGWP It crashes 😛 I revert this PR

**Comment by quentinguidee** [comment]
I force reverted `omega-dev` to 5e95afe9e47a179cb4ff30aaf77eea2da03817df

**Comment by LeGmask** [comment]
I'm just stupid

**Comment by quentinguidee** [comment]
IMG_20200129_130037

**Comment by LeGmask** [comment]
ptdr

**Pull request merged**
