### PR TITLE
External application, API v2

### PR DESCRIPTION
**Pull request by zardam**
I have done a big update of the API, and tried to merge KhiCAS dedicated API and the generic one. There is some regression for KhiCAS (no more DFU inside the app, mainly). I'm still working on this point.

It is now possible to access the pseudo file systems of the calculator, and the NES emulator is also upgraded to fetch ROM uploaded as "custom" file from the online tool, so multiple games is now possible :)

### CODE REVIEW

**Comment by zardam** [comment]
I will block the access to the custom files when the exam mode is activated. I think it is enough to be fully compliant, as no user data will be accessible.

A doc reader will happen, for sure, but if a student really want to cheat, I think it is really really easy, not only with the numworks calculator.

**Comment by M4xi1m3** [comment]
What are you calling custom files? Are KhiCAS and Periodic custom files?

**Comment by zardam** [comment]
The NES ROMs you can add from the web pages.

**Comment by MixedMatched** [comment]
We could try an asymmetric key pair to sign "approved" apps. Bypassing that would be easy for compiled versions at a user's machine, but (nearly) impossible for a precompiled version. Although it might be hard to calculate sums and keys on the calculator.

**Comment by M4xi1m3** [comment]
This is an idea to consider but could lead to an exam mode that takes some time to be enabled (not as extreme as the TI83PCE tho)

**Comment by quentinguidee** [comment]
Thanks @zardam ! Is this PR finished?

**Comment by zardam** [comment]
Yes, it is finished. I added the filtering of the custom files because there was some concern about the "exam mode" compliance.

**Comment by quentinguidee** [comment]
Okay perfect! It’s merged 😉  Thank you very much @zardam !!

**Pull request merged**
