### PR TITLE
Place math preferences into their own submenu

### PR DESCRIPTION
**Pull request by MixedMatched**
Moves AngleUnit, DisplayMode, EditionMode, and WritingFormat into a submenu for math options. Also fixes a couple miscellaneous warnings and bugs in settings.

### CODE REVIEW

**Comment by RedGl0w** [comment]
Ah :'(
Couldn't you just wait until my PR was merged :'(
And I have an idea for this PR : why don't we put the settings for a app in the app, like on the casio graph 35+E, which has a keyboard shortcut to access to per apps settings ?

**Comment by MixedMatched** [comment]
@RedGl0w I'll change whichever PR doesn't get accepted.

How would we present the per-app settings in an intuitive way? Also which apps need specific settings? These math settings apply to every app that display expressions.

**Comment by RedGl0w** [comment]
I'll add a sub controller, which is accessible by pressing shift+home, and for graph, calculation, regression, ... the settings will be practically the same, until we add https://github.com/numworks/epsilon/pull/954

**Comment by quentinguidee** [comment]
Merged! Thanks!

**Pull request merged**
