### PR TITLE
Revise LED submenu to allow for selectable colors

### PR DESCRIPTION
**Pull request by MixedMatched**
I don't have a physical device with me, so if someone could check if the LED color actually works, that would be cool. 

WIP: 
- [ ] slight numerical inconsistencies in the gauges that cause them to be slightly offset. 
- [ ] translate I18n references

### CODE REVIEW

**Comment by quentinguidee** [comment]
[Revise LED submenu to allow for choosable colors](https://trello.com/c/ebSOMLZC/24-revise-led-submenu-to-allow-for-choosable-colors)

**Comment by MixedMatched** [comment]
KDColors generated by this are interpreted incorrectly on my device's LED

**Comment by M4xi1m3** [comment]
I know why it doesn't interpret the colors correctly :

https://github.com/Omega-Numworks/Omega/blob/omega-master/ion/src/device/shared/drivers/led.cpp#L31

You can only have 8 different colors for exam mode.

**Comment by MixedMatched** [comment]
Seeing as we now force colors per mode of examination, this PR is now deprecated.

**Pull request closed without merging**
