### PR TITLE
Update German translations (base.de.i18n)

### PR DESCRIPTION
**Pull request by RedGl0w**
Corrected some language errors

### CODE REVIEW

**Comment by MixedMatched** [comment]
Should it be "BLau," and not "Blau"?

**Comment by RedGl0w** [comment]
I don't think so
I've learned that and I've checked if it is right
why?

**Comment by MixedMatched** [comment]
Okay. I don't know the language, but the capitol second letter just looked odd to me. Are there a lot of German words like that?

**Comment by RedGl0w** [comment]
like what? 
without capital letters on the second word? 
In German normally,  all the first letter of all names are capital

**Comment by MixedMatched** [comment]
The capital on the second letter, like in "BLau " on line 29:
`ColorBlue = "BLau "`

**Comment by RedGl0w** [comment]
AHHHH
I haven't seen that
You're right
sorry...

**Comment by quentinguidee** [comment]
Merged! Thank you!!

**Pull request merged**
