### PR TITLE
[Feature] Some "Freedom Units"

### PR DESCRIPTION
**Pull request by 0b101**
There are currently no translations

### CODE REVIEW

**Comment by quentinguidee** [comment]
@0b101 Thank you!! :)

@Gegenter You can say here the HU translations ? :)

**Comment by Gegenter** [comment]
Us customary angolszász mértékegységek
Yard yard
Foot láb
Mile mérföld
Ounce uncia 
Pound  font 
Inch hüvelyk
Us ton amerikai tonna

**Comment by RedGl0w** [comment]
> Us customary angolszász mértékegységek
> Yard yard
> Foot láb
> Mile mérföld
> Ounce uncia
> Pound font
> Inch hüvelyk
> Us ton amerikai tonna

You could make a review

**Comment by Lelahelry** [comment]
Adding some other units, like calories for example could be useful too. I have no particular ones in mind but feel free to suggest.

**Comment by quentinguidee** [comment]
See #257

**Comment by Lelahelry** [comment]
I had an idea: add radiation units like Sieverts (Sv) milliSieverts (mSv) and roentgens, to name a few.

**Pull request merged**
