### PR TITLE
[Feature] Root setting

### PR DESCRIPTION
**Pull request by LeGmask**
As requested by myself in #230 and  by @Lelahelry  in #193 : 
--------------------------------------------------------------------------------
##Improve Root keys : 

image
- Setting in math

image
- 3 types of Root

- [x] Traduction

### CODE REVIEW

**Comment by quentinguidee** [comment]
Hi @LeGmask ! Thank you for this PR!
I just think that the settings names should be changed ("Racine Carrée" "Racine carrée" and "Racine"). However, I like the expression on the right of the cells :)

**Comment by LeGmask** [comment]
Rename it as you wan't ...
And fixed with translation 
Racine carrée, Racine carré and Racine

**Comment by 0b101** [comment]
Can you make this also change how log() behaves?

**Comment by quentinguidee** [comment]
@0b101 Yeah we should unify these two settings

**Comment by LeGmask** [comment]
okay i'll do that

**Comment by LeGmask** [comment]
I'll do an other pr, this one is too lazy

**Pull request closed without merging**
