### PR TITLE
FCC ID fix

### PR DESCRIPTION
**Pull request by LeGmask**
Okay well i'm just stupid, and forgot to adapt to fccId cell 🤦‍♂️

### CODE REVIEW

**Comment by LeGmask** [comment]
this time normaly is the good one

**Comment by LeGmask** [comment]
okay well I have test but it just pull the same probleme on the upper case lul

**Comment by LeGmask** [comment]
dunno if this pr should finish because this should fix with Epsilon 13 ?

**Comment by quentinguidee** [comment]
If you're sure it'll be fixed in E13, yes you can close it

**Comment by LeGmask** [comment]
redgl0w says that should be fix, but dunno

**Comment by LeGmask** [comment]
Since E13 should fix that, I doesn't finish this pr anymore

**Pull request closed without merging**
