### PR TITLE
[Feature] Add root and log setting

### PR DESCRIPTION
**Pull request by LeGmask**
Add new setting fuction :
image
image

- default
image

- Default with arg
image

- Empty with arg
image

### CODE REVIEW

**Comment by quentinguidee** [comment]
I'm not a fan of the name `Function`. But Idk what to put instead. If someone has an idea 👌

**Comment by LeGmask** [comment]
Something like expression format is better ?

**Comment by quentinguidee** [comment]
Yes way better!

**Comment by LeGmask** [comment]
Okay done @quentinguidee you can merge if you wan't

**Comment by quentinguidee** [comment]
Thank you @LeGmask ! It works as expected :)

I just have one problem with your PR :

screenshot-2

**Comment by LeGmask** [comment]
Okay, but with just expression is okay ?

**Comment by quentinguidee** [comment]
Yeah why not

**Comment by LeGmask** [comment]
Yeah i'll do that, and there also some traduction that are do the same thing inside the setting but I know, will be fix

**Comment by LeGmask** [comment]
Oh I know format expression ...

**Comment by LeGmask** [comment]
Okay time for me to go back and work 😉

**Comment by LeGmask** [comment]
It's ready to be merged @quentinguidee :wink:

**Comment by quentinguidee** [comment]
Is it possible to squash all the commits ?

**Comment by quentinguidee** [comment]
Thank you very much!!

**Pull request merged**
