### PR TITLE
[Feature] Integrate ulab

### PR DESCRIPTION
**Pull request by KaiJan57**
This pull request integrates ulab-micropython, which is a numpy replacement for micropython. This adds functionality (e.g. array manipulation in python), however, it comes at the cost of making Omega less easy on resources (and requiring a higher maintenance effort, of course).

### CODE REVIEW

**Comment by quentinguidee** [comment]
Thank you very much! :) We'll integrate this ASAP!

If you want to talk with the team, you can join our Discord server here :

<a href="https://discord.gg/hjH3gtd">Discord</a>

https://discord.gg/hjH3gtd

Thank you! :)

**Comment by KaiJan57** [comment]
Regarding the binary size, I actually haven't tested, but that probably depends on the branch on which this pull request is applied. As this pull request doesn't change anything at the core of Omega, I believe that it will also work on different hardware. I however tested these changes successfully on the android simulator and my N0110.

**Comment by coco33920** [comment]
I've compiled your branch ( so with omega-dev ) we are at ~1013kibibytes where the last omega-dev branch is at ~979kibibytes

**Comment by KaiJan57** [comment]
Is there any way to analyse what is using up all that memory?

**Comment by M4xi1m3** [comment]
We have a way to do that for the RAM map but idk if it's possible for flash. Will have to check.

**Comment by KaiJan57** [comment]
Ah I guess the main issue is ulab's dependency on python arrays! Still, a "ROM map" would certainly help...

**Comment by coco33920** [comment]
Since the only difference between the main omega-dev branch and yours yeah i think that's the dependency witch use that much space

**Comment by KaiJan57** [comment]
What are we going to do, then? Create a new branch that maintains an "Omega with ulab" version?

**Comment by KaiJan57** [comment]
Switching branch...

**Pull request closed without merging**
