### PR TITLE
#53 External application launcher (with KhiCAS API)

### PR DESCRIPTION
**Pull request by zardam**
It is compatible with https://zardam.github.io/nw-external-apps/

### CODE REVIEW

**Comment by RedGl0w** [comment]
I think it's n0110, and not n110...

**Comment by MixedMatched** [comment]
Is this PR going to break compatibility with the N0100? I know the external functionality won't work with it, but will the firmware work at all for it?

**Comment by zardam** [comment]
It should not break the N0100. Just don't include the "external" app.

I'm trying to remove the specific KhiCAS API and integrate the useful functions in the regular API, but there is still a lot of work to be done. My idea is to minimize the changes in epsilon to lower the amount of work needed to follow epsilon updates (ideally, no changes outside of the external app folder).

**Comment by zardam** [comment]
For the simulator, there is an empty app statically linked. It is possible to replace the app folder inside the external application with a real one, to debug it on the simulator. it's a little bit rough but working. I'm currently working on Nofrendo and KhiCAS like this, I will push everything when done.

**Comment by quentinguidee** [comment]
Thank you very much for this PR @zardam !! It's now merged in the dev branch ;)

**Pull request merged**
