### PR TITLE
Omega with epsilon 15.5

### PR DESCRIPTION
**Pull request by RedGl0w**
- Remove OTP lock
- Moved save storage to specific file (TODO : implement in the JNIEnv the storage instead of SDL wrapper)

### CODE REVIEW

**Comment by M4xi1m3** [comment]
Seems really weird that the CI fails on windows and linux, looks like its for the same reason, I'll try taking a look.

**Comment by RedGl0w** [comment]
> Seems really weird that the CI fails on windows and linux, looks like its for the same reason, I'll try taking a look.

https://github.com/Omega-Numworks/Omega/pull/536

**Comment by M4xi1m3** [comment]
fair enough, should I merge it and try re-run the CI ?

**Comment by RedGl0w** [comment]
> fair enough, should I merge it and try re-run the CI ?

you can merge. I'll try to pull omega-dev asap

**Comment by M4xi1m3** [comment]
Merged #536, re-running the tests, we'll see if it passes.

**Pull request merged**
