### PR TITLE
Free 1776 bytes of heap by making sTableRows const

### PR DESCRIPTION
**Pull request by zardam**

### CODE REVIEW

**Comment by quentinguidee** [comment]
Hi @zardam ! Thank you for this PR :)

Are you sure the trigonometry is working with this ? One day cos(0) and e^(iπ) causes crash with this optimisation, so we did this : https://github.com/Omega-Numworks/Omega/commit/26d3466fec346de53d9a231e04367ac130846f5e
(see issue #122)

**Comment by zardam** [comment]
Very strange... I tested cos(0) and e^(iπ) on a n110 without any problem, and I don't see how adding "const" to sTableRows can cause an issue, as there is no write acces to this array anywhere.

**Comment by quentinguidee** [comment]
Yeah it was very strange.... I'll retry and if it works I merge! But yeah @boricj did this change and it crashed...

**Comment by MixedMatched** [comment]
It was because static was removed in the original. It allowed changes to the trig cheat table when calculations were done.

**Comment by quentinguidee** [comment]
@MixedMatched Yes I didn't see that ._. Everything's working! Will be available on Omega 1.19.1 !

Thank you @zardam :)

**Pull request merged**
